# ===================================
#  List Behavior Config
# ===================================

# Model List Column configuration
list: $/bookrr/store/models/shop/columns.yaml

# Model Class name
modelClass: Bookrr\Product\Models\Products

# List Title
title: Manage Shops

# Link URL for each record
recordUrl: bookrr/store/shop/update/:id

# Message to display if the list is empty
noRecordsMessage: backend::lang.list.no_records

# Records to display per page
recordsPerPage: 10

# Display page numbers with pagination, disable to improve performance
showPageNumbers: true

# Displays the list column set up button
showSetup: true

# Displays the sorting link on each column
showSorting: true

# Default sorting column
# defaultSort:
#     column: created_at
#     direction: desc

# Display checkboxes next to each record
showCheckboxes: true

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: list_toolbar

    # Search widget configuration
    search:
        prompt: backend::lang.list.search_prompt

customViewPath: $/bookrr/store/controllers/shop/list